# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025 Toradex

ifdef CONFIG_TARGET_TORADEX_OSM_IMX93
obj-y += osm-imx93.o
endif

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += lpddr4x_timing.o
endif
